name: 'Portfolio Action'
description: 'Builds a personal portfolio/resume static site from YAML and Markdown'
branding:
  icon: 'globe'
  color: 'blue'

inputs:
  data_dir:
    description: 'Directory containing YAML data files'
    default: '.'
  pages_dir:
    description: 'Directory containing markdown pages'
    default: 'pages'
  blog_dir:
    description: 'Directory containing blog post markdown files'
    default: 'blog'
  media_dir:
    description: 'Directory containing static media assets'
    default: 'media'
  output_dir:
    description: 'Build output directory'
    default: '_site'
  base_path:
    description: 'Base path for the site (e.g. /repo-name/ for GitHub Pages project sites)'
    default: '/'
  site_url:
    description: 'Full site URL for SEO (sitemap, RSS). Auto-detected from GITHUB_REPOSITORY if not set.'
    default: ''
  build_date:
    description: 'Override build date (YYYY-MM-DD) for reproducible builds and blog scheduling'
    default: ''
  pdf:
    description: 'Install Chrome for PDF generation (set false to skip Chrome setup and save install time)'
    default: 'true'

outputs:
  output_path:
    description: 'Path to the built site directory'
    value: ${{ inputs.output_dir }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install build dependencies
      shell: bash
      run: npm ci
      working-directory: ${{ github.action_path }}

    - name: Setup Chrome for PDF generation
      if: inputs.pdf != 'false'
      uses: browser-actions/setup-chrome@latest

    - name: Install Puppeteer for PDF generation
      if: inputs.pdf != 'false'
      shell: bash
      run: npm install puppeteer && npx puppeteer browsers install chrome
      working-directory: ${{ github.action_path }}

    - name: Build site
      shell: bash
      run: |
        node ${{ github.action_path }}/src/cli.js \
          --data-dir "${{ inputs.data_dir }}" \
          --pages-dir "${{ inputs.pages_dir }}" \
          --blog-dir "${{ inputs.blog_dir }}" \
          --media-dir "${{ inputs.media_dir }}" \
          --output-dir "${{ inputs.output_dir }}" \
          --base-path "${{ inputs.base_path }}" \
          --site-url "${{ inputs.site_url }}" \
          --build-date "${{ inputs.build_date }}" \
          ${{ inputs.pdf == 'false' && '--no-pdf' || '' }}
      working-directory: ${{ github.workspace }}
