lang: en
theme:
  primary: '#6366f1'
  accent: '#f97316'
  mode: system
favicon: 'media/profile.png'
og_image: ''
analytics_id: ''
custom_domain: ''
site_url: 'https://jinglemansweep.github.io/portfolio-action'
i18n_file: ''

hero:
  background: ''
  overlay_opacity: 0.6
  style: gradient

visibility:
  education: all
  experience: all
  experience_company: print
  projects: all
  community: all
  accreditations: all
  skills: all
  blog: all
  contact_email: all
  contact_phone: none
  location: all
  contact_website: all
  links: all

documents:
  pdf: true
  docx: true
  page_size: A4
  filename: resume

seo:
  robots:
    indexing: true
    follow_links: true
  sitemap: true
  llms_txt: true
  rss: true
